service: defender-test-project
configValidationMode: off

frameworkVersion: '3'

provider:
  name: defender

functions:
  hello:
    name: 'Hello world from serverless'
    path: './hello-world'

plugins:
  - ../defender-serverless


